/* 
Problem 45: Triangular, pentagonal, and hexagonal

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle    Tn=n(n+1)/2    1, 3, 6, 10, 15, ...
Pentagonal  Pn=n(3n−1)/2   1, 5, 12, 22, 35, ...
Hexagonal   Hn=n(2n−1)     1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.
Find the next triangle number that is also pentagonal and hexagonal.
*/

function triPentaHexa(n) {
    for (let k = 1; true; k++) {
        let triangle = getTriangle(k);

        if (triangle < n) continue;

        if (isPentagon(triangle) && isHexagon(triangle)) return triangle;
    }
}

function getTriangle(n) {
    return n * (n + 1) / 2;
}

function isPentagon(num) {
    let delta = Math.sqrt(1 + 24 * num);
    let bhaskara = (1 + delta) / 6;
    return bhaskara === Math.floor(bhaskara);
}

function isHexagon(num) {
    let delta = Math.sqrt(1 + 8 * num);
    let bhaskara = (1 + delta) / 4;
    return bhaskara === Math.floor(bhaskara);
}

module.exports = { triPentaHexa };