/* 
Problem 44: Pentagon numbers

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimized; what is the value of D?
*/

function pentagonNumbers() {
    let pentagons = [];
    let n = 1;

    while (true) {
        let nextPentagon = getPengatonNum(n);

        for (let i = 0; i < pentagons.length; i++) {
            let diff = nextPentagon - pentagons[i];
            if (
                isPentagon(nextPentagon + pentagons[i])
                && isPentagon(diff)
            ) {
                return diff;
            }
        }

        pentagons.push(nextPentagon);
        n++;
    }
}

function getPengatonNum(n) {
    return n * (3*n - 1) / 2;
}

function isPentagon(num) {
    let delta = Math.sqrt(1 + 24 * num);
    let bhaskara = (1 + delta) / 6;
    return bhaskara === Math.floor(bhaskara);
}

module.exports = { pentagonNumbers };